"""add_maintenance_management_models

Revision ID: 0c1f52186a44
Revises: 004_milestone2_enhancements
Create Date: 2026-10-05 10:17:13.973731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0c1f52186a44'
down_revision: Union[str, Sequence[str], None] = '004_milestone2_enhancements'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('service_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('service_center', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_maintenance_id'), 'maintenance_records', ['maintenance_id'], unique=True)
    op.create_index(op.f('ix_maintenance_records_scheduled_date'), 'maintenance_records', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_maintenance_records_status'), 'maintenance_records', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_records_vehicle_id'), 'maintenance_records', ['vehicle_id'], unique=False)
    op.create_table('maintenance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=True),
    sa.Column('new_status', sa.String(length=40), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_history_maintenance_id'), 'maintenance_history', ['maintenance_id'], unique=False)
    op.alter_column('shipments', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_maintenance_history_maintenance_id'), table_name='maintenance_history')
    op.drop_table('maintenance_history')
    op.drop_index(op.f('ix_maintenance_records_vehicle_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_status'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_scheduled_date'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_maintenance_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    # ### end Alembic commands ###